/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package internalPages;

import java.awt.Color;
import config.Session;
import config.configclass;
import net.proteanit.sql.DbUtils;
import students.Grades;
/**
 *
 * @author izana
 */
public class studentprofile extends javax.swing.JFrame {

    /** Creates new form studentprofile */
    public studentprofile() {
     initComponents();
    Session sess = Session.getInstance();
    p_name.setText(sess.getName());
    p_course.setText(sess.getcourse());
    p_section.setText(sess.getsection());
    // Email fallback: if session email looks invalid, read from DB
    String email = sess.getEmail();
    if (email == null || email.trim().isEmpty() || email.trim().matches("^\\d+$")) {
        try {
            configclass conf = new configclass();
            String dbEmail = conf.getSingleString("SELECT email FROM tbl_account WHERE u_id = ?", sess.getId());
            p_email.setText(dbEmail != null ? dbEmail : "");
        } catch (Exception ex) {
            p_email.setText("");
        }
    } else {
        p_email.setText(email);
    }
    p_id.setText(String.valueOf(sess.getId()));
    }
Color navcolor = new Color(102,102,102);
    Color headcolor = new Color(102,102,102);
    Color bodycolor = new Color(204,204,204);
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        p_name = new javax.swing.JLabel();
        p_id = new javax.swing.JLabel();
        p_course = new javax.swing.JLabel();
        p_section = new javax.swing.JLabel();
        p_email = new javax.swing.JLabel();
        course = new javax.swing.JLabel();
        section = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        mygrades = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SEMREP = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        majorsubrep = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile icon.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 160));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 190, 190));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("EMAIL:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("FULL NAME:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 150, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("STUDENT ID: ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 50));

        p_name.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jPanel2.add(p_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 140, 30));

        p_id.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jPanel2.add(p_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 130, 30));

        p_course.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jPanel2.add(p_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 140, 30));

        p_section.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jPanel2.add(p_section, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 110, 30));

        p_email.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jPanel2.add(p_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 180, 30));

        course.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        course.setText("Course:");
        jPanel2.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 100, -1));

        section.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        section.setText("Section:");
        jPanel2.add(section, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 100, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 230));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mygrades.setBackground(new java.awt.Color(153, 153, 153));
        mygrades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mygradesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mygradesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mygradesMouseExited(evt);
            }
        });
        mygrades.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-grades-100.png"))); // NOI18N
        mygrades.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 120));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MY GRADES");
        mygrades.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 116, 230, 30));

        jPanel6.add(mygrades, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 230, 150));

        SEMREP.setBackground(new java.awt.Color(153, 153, 153));
        SEMREP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SEMREPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SEMREPMouseExited(evt);
            }
        });
        SEMREP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-graph-report-100.png"))); // NOI18N
        SEMREP.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 130));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Semester Reports ");
        SEMREP.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 126, 220, 20));

        jPanel6.add(SEMREP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 230, 150));

        majorsubrep.setBackground(new java.awt.Color(153, 153, 153));
        majorsubrep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                majorsubrepMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                majorsubrepMouseExited(evt);
            }
        });
        majorsubrep.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-subjects-100.png"))); // NOI18N
        majorsubrep.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 130));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Major Subjects Report ");
        majorsubrep.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 230, 30));

        jPanel6.add(majorsubrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 230, 150));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 830, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mygradesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mygradesMouseEntered
        mygrades.setBackground(bodycolor);
    }//GEN-LAST:event_mygradesMouseEntered

    private void mygradesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mygradesMouseExited
        mygrades.setBackground(navcolor);
    }//GEN-LAST:event_mygradesMouseExited

    private void SEMREPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SEMREPMouseEntered
        SEMREP.setBackground(bodycolor);
    }//GEN-LAST:event_SEMREPMouseEntered

    private void SEMREPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SEMREPMouseExited
        SEMREP.setBackground(navcolor);
    }//GEN-LAST:event_SEMREPMouseExited

    private void majorsubrepMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_majorsubrepMouseEntered
        majorsubrep.setBackground(bodycolor);
    }//GEN-LAST:event_majorsubrepMouseEntered

    private void majorsubrepMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_majorsubrepMouseExited
        majorsubrep.setBackground(navcolor);
    }//GEN-LAST:event_majorsubrepMouseExited

    private void mygradesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mygradesMouseClicked
    Grades g = new Grades();
    g.setLocationRelativeTo(null); // This will work now!
    g.setVisible(true);
    }//GEN-LAST:event_mygradesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentprofile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SEMREP;
    private javax.swing.JLabel course;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel majorsubrep;
    private javax.swing.JPanel mygrades;
    public javax.swing.JLabel p_course;
    public javax.swing.JLabel p_email;
    public javax.swing.JLabel p_id;
    public javax.swing.JLabel p_name;
    public javax.swing.JLabel p_section;
    private javax.swing.JLabel section;
    // End of variables declaration//GEN-END:variables

}
