/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import newpackage.Landingpage;
/**
 *
 * @author izana
 */
public class userprofile extends javax.swing.JInternalFrame {

    /**
     * Creates new form userprofile
     */
    public userprofile() {
        initComponents();
    }
    
    
    
    public userprofile(int userId, String username, String email, String name) {
    initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    // Display the student information on the labels
    jLabel2.setText("FULL NAME: " + name);
    jLabel4.setText("STUDENT ID: " + username);
    jLabel1.setText("EMAIL: " + email);
    // jLabel3 is for contact number - you can add this later from student table
}
    
    
    
    Color navcolor = new Color(102,102,102);
    Color headcolor = new Color(102,102,102);
    Color bodycolor = new Color(204,204,204);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        p_name = new javax.swing.JLabel();
        p_id = new javax.swing.JLabel();
        p_email = new javax.swing.JLabel();
        LOGOUT = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        mygrades = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SEMREP = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        majorsubrep = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile icon.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 160));

        jPanel1.add(jPanel3);
        jPanel3.setBounds(600, 20, 190, 190);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("EMAIL:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 140, 90, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("FULL NAME:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 10, 150, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("STUDENT ID: ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 80, 168, 50);

        p_name.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jPanel1.add(p_name);
        p_name.setBounds(180, 24, 190, 20);

        p_id.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jPanel1.add(p_id);
        p_id.setBounds(180, 90, 170, 30);

        p_email.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jPanel1.add(p_email);
        p_email.setBounds(110, 150, 180, 30);

        LOGOUT.setText("Log out");
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });
        jPanel1.add(LOGOUT);
        LOGOUT.setBounds(510, 200, 69, 23);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 230));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mygrades.setBackground(new java.awt.Color(153, 153, 153));
        mygrades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mygradesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mygradesMouseExited(evt);
            }
        });
        mygrades.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-grades-100.png"))); // NOI18N
        mygrades.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 130));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MY GRADES");
        mygrades.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 116, 230, 30));

        jPanel6.add(mygrades, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 230, 150));

        SEMREP.setBackground(new java.awt.Color(153, 153, 153));
        SEMREP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SEMREPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SEMREPMouseExited(evt);
            }
        });
        SEMREP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-graph-report-100.png"))); // NOI18N
        SEMREP.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 130));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Semester Reports ");
        SEMREP.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 126, 220, 20));

        jPanel6.add(SEMREP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 230, 150));

        majorsubrep.setBackground(new java.awt.Color(153, 153, 153));
        majorsubrep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                majorsubrepMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                majorsubrepMouseExited(evt);
            }
        });
        majorsubrep.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-subjects-100.png"))); // NOI18N
        majorsubrep.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 130));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Major Subjects Report ");
        majorsubrep.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 230, 30));

        jPanel6.add(majorsubrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 230, 150));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 840, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mygradesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mygradesMouseEntered
        mygrades.setBackground(bodycolor);
    }//GEN-LAST:event_mygradesMouseEntered

    private void mygradesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mygradesMouseExited
        mygrades.setBackground(navcolor);
    }//GEN-LAST:event_mygradesMouseExited

    private void SEMREPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SEMREPMouseEntered
         SEMREP.setBackground(bodycolor);
    }//GEN-LAST:event_SEMREPMouseEntered

    private void SEMREPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SEMREPMouseExited
               SEMREP.setBackground(navcolor);

    }//GEN-LAST:event_SEMREPMouseExited

    private void majorsubrepMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_majorsubrepMouseEntered
        majorsubrep.setBackground(bodycolor);
    }//GEN-LAST:event_majorsubrepMouseEntered

    private void majorsubrepMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_majorsubrepMouseExited
               majorsubrep.setBackground(navcolor);
    }//GEN-LAST:event_majorsubrepMouseExited

    private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTActionPerformed
        Landingpage lf = new Landingpage();
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LOGOUTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LOGOUT;
    public javax.swing.JPanel SEMREP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    public javax.swing.JPanel majorsubrep;
    public javax.swing.JPanel mygrades;
    public javax.swing.JLabel p_email;
    public javax.swing.JLabel p_id;
    public javax.swing.JLabel p_name;
    // End of variables declaration//GEN-END:variables

    public void setLocationRelativeTo(Object object) {
        
    }
}
