/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Teacher;

import config.Session;
import config.configclass;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author izana
 */
public class teacherprofile extends javax.swing.JFrame {

    /**
     * Creates new form teacherprofile
     */
    public teacherprofile() {
          initComponents();
    Session sess = Session.getInstance();
    
    // Common labels for both Student and Teacher
    p_name.setText(sess.getName());
    p_id.setText("" + sess.getId());
    p_email.setText(sess.getEmail());
    
    // Department logic (guard against null to avoid NPE)
    String dept = sess.getDepartment();
    if (dept == null || dept.equals("N/A")) {
        // If no department (or explicitly N/A), hide the department labels
        t_department.setVisible(false);
        Deparment.setVisible(false); // The "Department:" text label
    } else {
        // If it's a teacher, show it
        t_department.setText(dept);
        t_department.setVisible(true);
        Deparment.setVisible(true);
    }

    // Email fallback: if the session email looks invalid (numeric or empty), fetch from tbl_account
    String email = sess.getEmail();
    if (email == null || email.trim().isEmpty() || email.trim().matches("^\\d+$")) {
        try {
            configclass conf = new configclass();
            String dbEmail = conf.getSingleString("SELECT email FROM tbl_account WHERE u_id = ?", sess.getId());
            if (dbEmail != null) {
                p_email.setText(dbEmail);
            } else {
                p_email.setText("");
            }
        } catch (Exception ex) {
            p_email.setText("");
        }
    } else {
        p_email.setText(email);
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        p_name = new javax.swing.JLabel();
        p_id = new javax.swing.JLabel();
        p_email = new javax.swing.JLabel();
        Deparment = new javax.swing.JLabel();
        t_department = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Students = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EncodeGrades = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        announcement = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile icon.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 160));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 190, 190));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("EMAIL:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("FULL NAME:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Teacher ID:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 50));

        p_name.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jPanel2.add(p_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 24, 190, 30));

        p_id.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jPanel2.add(p_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 170, 30));

        p_email.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jPanel2.add(p_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 180, 30));

        Deparment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Deparment.setText("Department:");
        jPanel2.add(Deparment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        t_department.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jPanel2.add(t_department, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 130, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 260));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Students.setBackground(new java.awt.Color(102, 102, 102));
        Students.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/students.png"))); // NOI18N
        Students.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 150));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Students");
        Students.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 140, 180, -1));

        jPanel4.add(Students, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 180, 180));

        EncodeGrades.setBackground(new java.awt.Color(102, 102, 102));
        EncodeGrades.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/encode grades.png"))); // NOI18N
        EncodeGrades.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 140));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Encode Grades");
        EncodeGrades.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 140, 180, -1));

        jPanel4.add(EncodeGrades, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 180, 180));

        announcement.setBackground(new java.awt.Color(102, 102, 102));
        announcement.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/announce.png"))); // NOI18N
        announcement.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 140));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Announcements");
        announcement.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 140, -1, -1));

        jPanel4.add(announcement, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 200, 180));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 860, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacherprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacherprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacherprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacherprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacherprofile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Deparment;
    private javax.swing.JPanel EncodeGrades;
    private javax.swing.JPanel Students;
    private javax.swing.JPanel announcement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JLabel p_email;
    public javax.swing.JLabel p_id;
    public javax.swing.JLabel p_name;
    private javax.swing.JLabel t_department;
    // End of variables declaration//GEN-END:variables
}
