/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Teacher;
import java.awt.Color;
import config.configclass;
import net.proteanit.sql.DbUtils;
import javax.swing.*;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author izana
 */
public class TeacherSettings extends javax.swing.JInternalFrame {

    /**
     * Creates new form TeacherSettings
     */
    public TeacherSettings() {
       
        initComponents();
    
    // This removes the internal frame title bar
    this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
    BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
    bi.setNorthPane(null);
    
    // Load your data
    loadAccountData();
    }
    private void loadAccountData() {
    try {
        configclass config = new configclass();
        String sql = "SELECT * FROM tbl_teacher";
        config.displayData(sql, tbl_teacher);  // Changed from tablecontents to jTable1
        System.out.println("Data loaded successfully!");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
            "Cannot load data: " + ex.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
}
   
    Color navcolor = new Color(102,102,102);
    Color headcolor = new Color(102,102,102);
    Color bodycolor = new Color(204,204,204);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_teacher = new javax.swing.JTable();
        header = new javax.swing.JPanel();
        edit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        add = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        remove = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_teacher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "teacher_id", "u_id", "teacher_number", "full_name", "email", "contact_number", "department", "specialization"
            }
        ));
        jScrollPane1.setViewportView(tbl_teacher);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 910, 440));

        header.setBackground(new java.awt.Color(102, 102, 102));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edit.setBackground(new java.awt.Color(102, 102, 102));
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editMouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editMouseExited(evt);
            }
        });
        edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit profile");
        edit.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 10, 130, 20));

        header.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 140, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/editprofile.png"))); // NOI18N
        header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 130));

        add.setBackground(new java.awt.Color(102, 102, 102));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel3.setText("Add User");
        add.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        header.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 130, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/adduser.png"))); // NOI18N
        header.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 130));

        remove.setBackground(new java.awt.Color(102, 102, 102));
        remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeMouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeMouseExited(evt);
            }
        });
        remove.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel5.setText("Remove user");
        remove.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 20));

        header.add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 150, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/remove.png"))); // NOI18N
        header.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, 130));

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 140));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1230, 624));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseEntered
        edit.setBackground(bodycolor);
    }//GEN-LAST:event_editMouseEntered

    private void editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseExited
       edit.setBackground(navcolor);
    }//GEN-LAST:event_editMouseExited

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
    add.setBackground(bodycolor);
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
           add.setBackground(navcolor);

    }//GEN-LAST:event_addMouseExited

    private void removeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMouseEntered
      remove.setBackground(bodycolor);
    }//GEN-LAST:event_removeMouseEntered

    private void removeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMouseExited
             remove.setBackground(navcolor);

    }//GEN-LAST:event_removeMouseExited

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // Show a modal form to create a new teacher record
        JTextField uIdField = new JTextField();
        JTextField teacherNumField = new JTextField();
        JTextField fullNameField = new JTextField();
        JTextField emailField = new JTextField();
        JTextField contactField = new JTextField();
        JTextField deptField = new JTextField();
        JTextField specField = new JTextField();

        Object[] form = {
            "User ID (u_id):", uIdField,
            "Teacher Number:", teacherNumField,
            "Full Name:", fullNameField,
            "Email:", emailField,
            "Contact Number:", contactField,
            "Department:", deptField,
            "Specialization:", specField
        };

        int result = JOptionPane.showConfirmDialog(this, form, "Add Teacher", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result != JOptionPane.OK_OPTION) return;

        try {
            int u_id = Integer.parseInt(uIdField.getText().trim());
            String teacherNumber = teacherNumField.getText().trim();
            String fullName = fullNameField.getText().trim();
            String email = emailField.getText().trim();
            String contact = contactField.getText().trim();
            String department = deptField.getText().trim();
            String specialization = specField.getText().trim();

            if (teacherNumber.isEmpty() || fullName.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Teacher number and full name are required.", "Validation", JOptionPane.WARNING_MESSAGE);
                return;
            }

            configclass con = new configclass();
            String sql = "INSERT INTO tbl_teacher (u_id, teacher_number, full_name, email, contact_number, department, specialization) VALUES (?, ?, ?, ?, ?, ?, ?)";
            boolean ok = con.addRecordBool(sql, u_id, teacherNumber, fullName, email, contact, department, specialization);
            if (ok) {
                loadAccountData();
                JOptionPane.showMessageDialog(this, "Teacher added successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add teacher. Check console for details.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid numeric input for User ID.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error adding teacher: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_addMouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        int row = tbl_teacher.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to edit.");
            return;
        }
        try {
            Object idObj = tbl_teacher.getValueAt(row, 0);
            if (idObj == null) {
                JOptionPane.showMessageDialog(this, "Selected row has no teacher_id.");
                return;
            }
            int teacherId = Integer.parseInt(idObj.toString());

            String currentUId = tbl_teacher.getValueAt(row, 1) != null ? tbl_teacher.getValueAt(row, 1).toString() : "";
            String currentTeacherNumber = tbl_teacher.getValueAt(row, 2) != null ? tbl_teacher.getValueAt(row, 2).toString() : "";
            String currentFullName = tbl_teacher.getValueAt(row, 3) != null ? tbl_teacher.getValueAt(row, 3).toString() : "";
            String currentEmail = tbl_teacher.getValueAt(row, 4) != null ? tbl_teacher.getValueAt(row, 4).toString() : "";
            String currentContact = tbl_teacher.getValueAt(row, 5) != null ? tbl_teacher.getValueAt(row, 5).toString() : "";
            String currentDepartment = tbl_teacher.getValueAt(row, 6) != null ? tbl_teacher.getValueAt(row, 6).toString() : "";
            String currentSpecialization = tbl_teacher.getValueAt(row, 7) != null ? tbl_teacher.getValueAt(row, 7).toString() : "";

            JTextField uIdField = new JTextField(currentUId);
            JTextField teacherNumField = new JTextField(currentTeacherNumber);
            JTextField fullNameField = new JTextField(currentFullName);
            JTextField emailField = new JTextField(currentEmail);
            JTextField contactField = new JTextField(currentContact);
            JTextField deptField = new JTextField(currentDepartment);
            JTextField specField = new JTextField(currentSpecialization);

            Object[] form = {
                "User ID (u_id):", uIdField,
                "Teacher Number:", teacherNumField,
                "Full Name:", fullNameField,
                "Email:", emailField,
                "Contact Number:", contactField,
                "Department:", deptField,
                "Specialization:", specField
            };

            int result = JOptionPane.showConfirmDialog(this, form, "Edit Teacher", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (result != JOptionPane.OK_OPTION) return;

            int u_id = Integer.parseInt(uIdField.getText().trim());
            String teacherNumber = teacherNumField.getText().trim();
            String fullName = fullNameField.getText().trim();
            String email = emailField.getText().trim();
            String contact = contactField.getText().trim();
            String department = deptField.getText().trim();
            String specialization = specField.getText().trim();

            if (teacherNumber.isEmpty() || fullName.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Teacher number and full name are required.", "Validation", JOptionPane.WARNING_MESSAGE);
                return;
            }

            configclass con = new configclass();
            String sql = "UPDATE tbl_teacher SET u_id = ?, teacher_number = ?, full_name = ?, email = ?, contact_number = ?, department = ?, specialization = ? WHERE teacher_id = ?";
            boolean ok = con.updateRecord(sql, u_id, teacherNumber, fullName, email, contact, department, specialization, teacherId);
            if (ok) {
                loadAccountData();
                JOptionPane.showMessageDialog(this, "Teacher updated successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "No rows updated.");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid numeric input for User ID.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error updating teacher: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_editMouseClicked

    private void removeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMouseClicked
        int row = tbl_teacher.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to remove.");
            return;
        }
        try {
            Object idObj = tbl_teacher.getValueAt(row, 0);
            if (idObj == null) {
                JOptionPane.showMessageDialog(this, "Selected row has no teacher_id.");
                return;
            }
            int teacherId = Integer.parseInt(idObj.toString());
            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this teacher?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
            if (confirm != JOptionPane.YES_OPTION) return;

            configclass con = new configclass();
            boolean ok = con.deleteRecord("DELETE FROM tbl_teacher WHERE teacher_id = ?", teacherId);
            if (ok) {
                loadAccountData();
                JOptionPane.showMessageDialog(this, "Teacher removed.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to remove teacher.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error removing teacher: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_removeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherSettings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add;
    private javax.swing.JPanel edit;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel remove;
    private javax.swing.JTable tbl_teacher;
    // End of variables declaration//GEN-END:variables
}
